//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadingDropDown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.addresses = new HashSet<address>();
            this.states = new HashSet<state>();
        }
    
        public int country_id { get; set; }
        public string country_name { get; set; }
        public string country_abbrev { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<state> states { get; set; }
    }
}
